name: Publish artfiacts to Sonatype Repo

on: [push]

jobs:
  build-native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build native image
        run: |
          cd zwaves_jni
          sudo apt-get update
          sudo apt-get -y install clang gcc g++ zlib1g-dev libmpc-dev libmpfr-dev libgmp-dev mingw-w64 gcc-multilib
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
          rustup target add i686-pc-windows-gnu
          rustup target add x86_64-pc-windows-gnu
          rustup target add i686-unknown-linux-gnu
          rustup target add x86_64-unknown-linux-gnu
          ./build_all.sh
