name: Publish artfiacts to Sonatype Repo

on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.OSSRH_USERNAME }}
      PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      GPG_KEY_ID: ${{ secrets.OSSRH_GPG_KEY_ID }}
      GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo '${{ secrets.OSSRH_GPG_KEY }}' | base64 -d > secret.gpg
          ./zwaves_jni/build_all.sh
      - name: Publish Snapshot
        if: ${{ !contains(github.ref, '/tags/') }}
        run: |
          ./gradlew uploadArchives \
            -PsonatypeRepo=https://oss.sonatype.org/content/repositories/snapshots \
            -PwhisperSonatypeUsername='${{ secrets.OSSRH_USERNAME }}' \
            -PwhisperSonatypePassword='${{ secrets.OSSRH_PASSWORD }}' \
            -Psigning.secretKeyRingFile=../secret.gpg \
            -Psigning.keyId='${{ secrets.OSSRH_GPG_KEY_ID }}' \
            -Psigning.password='${{ secrets.OSSRH_GPG_PASSPHRASE }}'
      - name: Publish Release
        if: contains(github.ref, '/tags/')
        run: |
          ./gradlew uploadArchives closeAndReleaseRepository \
            -PsonatypeRepo=https://oss.sonatype.org/service/local/staging/deploy/maven2 \
            -PwhisperSonatypeUsername='${{ secrets.OSSRH_USERNAME }}' \
            -PwhisperSonatypePassword='${{ secrets.OSSRH_PASSWORD }}' \
            -Psigning.secretKeyRingFile=../secret.gpg \
            -Psigning.keyId='${{ secrets.OSSRH_GPG_KEY_ID }}' \
            -Psigning.password='${{ secrets.OSSRH_GPG_PASSPHRASE }}'